# Pandas series

A Series is a  one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

# creating series

In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\piyus\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\piyus\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\piyus\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\piyus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\piyus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\piyus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [76]:
import numpy as np
import pandas as pd

In [8]:
labels =['a','b','c'] # labels value
my_list =[10,20,30] #list 
arr = np.array([10,20,30]) #array
d = {1:10,2:20,3:30} #dictionary

In [10]:
pd.Series(my_list, index= labels) #labels value

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(arr) # array series

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(d) #dictionary

1    10
2    20
3    30
dtype: int64

# Data Frames

In [23]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [24]:
df # create data frame

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd. DataFrame(data)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selection and Indexing of Columns

In [30]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

# Creating a new column

In [41]:
df2["Designation"]= ["Doctor", "engineer","Doctor","Engineer"]

In [42]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

 # removing column

In [43]:
df2.drop('Designation',axis =1, inplace = True)

In [44]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# removing rows

In [48]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [49]:
df.loc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

# Selsecting subsets of rows and columns

In [51]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [53]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42


# Conditional Selection

In [56]:
# I only want to see those people whose age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [58]:
# i only wnt people whose age is above 30 and their city  must be paris.
df2[(df2['Age'] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

## Missing Data

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5] # here nan means null values 
}
df=pd.DataFrame(data)

In [4]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [8]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Remove Missimg Data

In [9]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.dropna() # help  to remove all nll values

     A  B    C    D
0  1.0  1  1.0  1.0

In [11]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [12]:
df.dropna(thresh =3) # here in the raw atleast 3 nun values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Filling the missing Data

In [13]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [15]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [18]:
values = {'A':0,'B':100, 'C':300, 'D':400}
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [19]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [20]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [22]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

# Mearging Joining & Concatination

Mearging 2 dataframe

In [23]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [24]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [25]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [28]:
pd.merge(employees,salaries,on='employee_id',how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [29]:
pd.merge(employees, salaries, on ='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [30]:
pd.merge(employees, salaries, on ='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [31]:
pd.merge(employees, salaries, on ='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

# Concatination of 2 dataframes

In [33]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [34]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [35]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [37]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [39]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**joining 2 data frames**

In [40]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [41]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [42]:
df2

   score
2     85
3     90
4     75

In [45]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [46]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

# Group By Aggregration

In [48]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df= pd.DataFrame(data)

In [49]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [56]:
# Group by Category and calculate the sum of Sales
cat=df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [58]:
# Group by Store and calculate the sum of Sales
cat=df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [59]:
# Group by multiple columns
# Group by Category and Store

cat=df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# Aggregation

In [62]:
df['Sales'].mean()

np.float64(187.5)

In [63]:
df['Sales'].median()

190.0

In [64]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [65]:
df['Sales'].min()

100

In [66]:
df['Sales'].max()

300

In [67]:
df['Sales'].count()

np.int64(8)

In [68]:
df['Sales'].std()

66.06274074155351

In [72]:
df['Sales'].agg(['mean','min','max','count','std','median',])

mean      187.500000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
median    190.000000
Name: Sales, dtype: float64

# PivotTables

In [81]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df =pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    844     36   John  January      Q1
1  2023-01-02       B   West    559     88   Mary  January      Q1
2  2023-01-03       C  North    390     96    Bob  January      Q1
3  2023-01-04       D  South    573     61  Alice  January      Q1
4  2023-01-05       A   East    428     11   John  January      Q1
5  2023-01-06       B   West    320     14   Mary  January      Q1
6  2023-01-07       C  North    504     97    Bob  January      Q1
7  2023-01-08       D  South    792     33  Alice  January      Q1
8  2023-01-09       A   East    779     70   John  January      Q1
9  2023-01-10       B   West    140     62   Mary  January      Q1
10 2023-01-11       C  North    478     35    Bob  January      Q1
11 2023-01-12       D  South    826     88  Alice  January      Q1
12 2023-01-13       A   East    214     91   John  January      Q1
13 2023-01-14       B   West    888     51   Mary  January      Q1
14 2023-01-15       C  North    579     62    Bob  January      Q1
15 2023-01-16       D  South    497     13  Alice  January      Q1
16 2023-01-17       A   East    517     58   John  January      Q1
17 2023-01-18       B   West    886     77   Mary  January      Q1
18 2023-01-19       C  North    959     31    Bob  January      Q1
19 2023-01-20       D  South    279     58  Alice  January      Q1

In [84]:
pd.pivot_table(df,values = 'Sales', index = 'Region', columns= "Product", aggfunc ='median')

Product      A      B      C      D
Region
East     517.0    NaN    NaN    NaN
North      NaN    NaN  504.0    NaN
South      NaN    NaN    NaN  573.0
West       NaN  559.0    NaN    NaN

In [85]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     556.4    NaN    NaN    NaN  53.2   NaN   NaN   NaN
North      NaN    NaN  582.0    NaN   NaN   NaN  64.2   NaN
South      NaN    NaN    NaN  593.4   NaN   NaN   NaN  50.6
West       NaN  558.6    NaN    NaN   NaN  58.4   NaN   NaN

# Cross Tabs

In [86]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

## OPERATIONS

In [99]:
df1= pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [95]:
df4

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [100]:
df1.shape

(5, 3)

In [101]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [102]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [104]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [105]:
df1['A']+ 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

# DataFrames Applying Functions

In [106]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [108]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [109]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500